name: CI/CD with GitHub Runner and EC2 Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t myapp:${{ github.sha }} .

      - name: Test locally
        run: |
          docker rm -f test || true
          docker run -d --name test -p 5000:5000 myapp:${{ github.sha }}
          sleep 5
          curl -s http://localhost:5000

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            docker rm -f myapp || true
            docker run -d --name myapp -p 5000:5000 myapp:${{ github.sha }}

