name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.REMOTE_HOST }}       # GitHub variable
          username: ${{ vars.REMOTE_USER }}   # GitHub variable
          key: ${{ secrets.AWS_SSH_KEY }}     # GitHub secret (private key)
          source: "./*"
          target: "/home/ubuntu"
          debug: true                         # enables debug output in logs

      - name: Restart App on Port 5000
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            fuser -k 5000/tcp || true
            cd /home/ubuntu
            nohup python3 app.py > app.log 2>&1 &
