name: CI with GitHub Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest   # GitHub-hosted runner

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t mycv-app:${{ github.sha }} .

      # 3️⃣ Run container locally for test (on port 5000)
      - name: Run container locally for test
        run: |
          docker rm -f test || true
          docker run -d --name test -p 5000:5000 mycv-app:${{ github.sha }}
          sleep 5

      # 4️⃣ Test with curl
        - name: Test with curl
    run: curl -s http://localhost:5000 | grep "Kashan Abbasi"

